pub const ROTORS: [(&str, char); 5] = [
    ("EKMFLGDQVZNTOWYHXUSPAIBRCJ", 'Q'), // I
    ("AJDKSIRUXBLHWTMCQGZNPYFVOE", 'E'), // II
    ("BDFHJLCPRTXVZNYEIWGAKMUSQO", 'V'), // III
    ("ESOVPZJAYQUIRHXLNFTGKDCMWB", 'J'), // IV
    ("VZBRGITYUPSDNHLXAWMJQOFECK", 'Z'), // V
];

pub const REFLECTORS: [&str; 3] = [
    "EJMZALYXVBWFCRQUONTSPIKHGD", // UKW-A
    "YRUHQSLDPXNGOKMIEBFZCWVJAT", // UKW-B
    "FVPJIAOYEDRZXWGCTKUQSBNMHL", // UKW-C
];